Work on topo dataset, kinda working, problem when saving:
This comes up when saving:

    OverflowError: Python int too large to convert to C long

Not sure which variable...